// Generated by https://quicktype.io
// Generated by https://quicktype.io

class ClientPost {
  int id;
  String cpf;
  String ie;
  String raz;
  String fan;
  String tel;
  dynamic cel;
  String logr;
  String num;
  String compl;
  String bai;
  String cidNom;
  String cidUf;
  String cep;
  dynamic lat;
  dynamic long;
  int precId;
  int vendId;
  String undExt;
  String appKey;
  bool ativ;

  ClientPost({
    this.id,
    this.cpf,
    this.ie,
    this.raz,
    this.fan,
    this.tel,
    this.cel,
    this.logr,
    this.num,
    this.compl,
    this.bai,
    this.cidNom,
    this.cidUf,
    this.cep,
    this.lat,
    this.long,
    this.precId,
    this.vendId,
    this.undExt,
    this.appKey,
    this.ativ,
  });

  ClientPost.fromJson(Map<String, dynamic> json)

      : id = json["id"],
        cpf = json["cpf"],
        ie = json["ie"],
        raz = json["raz"],
        fan = json["fan"],
        tel = json["tel"],
        cel = json["cel"],
        logr = json["logr"],
        num = json["num"],
        compl = json["compl"],
        bai = json["bai"],
        cidNom = json["cidNom"],
        cidUf = json["cidUf"],
        cep = json["cep"],
        lat = json["lat"],
        long = json["long"],
        precId = json["precId"],
        vendId = json["vendId"],
        undExt = json["undExt"],
        appKey = json["appKey"],
        ativ = json["ativ"];
      
} 
